//
//  FactProvider.swift
//  FunFacts
//
//  Created by Melissa Oveson on 3/24/18.
//  Copyright © 2018 Miss Geek Bunny. All rights reserved.
//

import GameKit

struct FactProvider {
    let facts = ["Ants stretch when they wake up in the morning.",
        "Ostriches can run faster than horses.",
        "Olympic gold medals are actually made of silver",
        "You are born with 300 bones; by the time you are an adult you will have 206",
        "It takes about 8 minutes for light from the Sun to reach Earth",
        "Some bamboo plants can grow almost a meter in just one day",
        "The state of Florida is bigger than England",
        "Some penguins can leap 2-3 meters out of the water",
        "On average, it takes 66 days to form a new habit",
        "Mammoths still walked the earth when the Great Pyramid was being built.",
        "During a 2004 episode of Sesame Street, Cookie Monster said that before he started eating cookies, his name was Sid.",
        "Mr. Rogers was an ordained minister.",
        "Horses can’t vomit.",
        "Before settling on the Seven Dwarfs we know today, Disney also considered Chesty, Tubby, Burpy, Deafy, Hickey, Wheezy, and Awful.",
        "The unkempt Shaggy of Scooby-Doo fame has a rather proper real name, Norville Rogers.",
        "A cat has 32 muscles in each ear.",
        "An ostrich’s eye is bigger than its brain.",
        "The characters Bert and Ernie, on Sesame Street, were named after Bert the cop and Ernie the taxi driver in Frank Capra’s \"It’s A Wonderful Life.\"",
        "In England, the Speaker of the House is not allowed to speak.",
        "\"Stewardesses\" is the longest word that is typed with only the left hand.",
        "A jellyfish is 95% water",
        "In Bangladesh, kids as young as 15 can be jailed for cheating on their finals.",
        "The starfish is one of the only animals who can turn it’s stomach inside-out.",
        "The elephant is the only mammal that can’t jump.",
        "Q is the only letter in the alphabet that does not appear in the name of any of the United States.",
        "The British once went to war over a sailor’s ear. It happened in 1739, when Britain launched hostilities against Spain because a Spanish officer had supposedly sliced off the ear of a ship’s captain named Robert Jenkins.",
        "There are no words in the dictionary that rhyme with: orange, purple, and silver.",
        "Fortune cookies were actually invented in America, in 1918, by Charles Jung.",
        "Chewing gum while peeling onions will keep you from crying.",
        "In England, in the 1880s, \"Pants\" was considered a dirty word.",
        "The strongest muscle in the body is the tongue.",
        "The Eiffel Tower is second only to the Golden Gate Bridge as a suicide location.",
        "The Matterhorn at Disneyland in Anaheim had a full basketball court at the very top of the structure, because at the time it was built the only structures that could be that tall were sports arenas.",
        "In the movie, ‘Star Wars’, during the scene in which Luke gets out of his X-wing fighter after blowing up the Death Star, he accidentally calls Princess Leia ‘Carrie’ (her real first name).",
        "The first product to have a UPC bar code on its packaging was Wrigley’s gum.",
        "Play-doh was first invented as a wallpaper cleaner.",
        "Astronaut Neil Armstrong first stepped on the moon with his left foot.",
        "The word ‘nerd’ was first coined by Dr. Seuss in ‘If I ran the Zoo’",
        "Boys who have unusual first names are more likely to have mental problems than boys with common names. Girls don’t seem to have this problem.",
        "Left-handedness is extremely common in twins. It is unusual, however, for both to be left-handed.",
        "Every time you lick a stamp, you’re consuming 1/10th of a calorie.",
        "Humans and dolphins are the only species that have sex for pleasure.",
        "Polar bears are left handed.",
        "A crocodile cannot stick its tongue out.",
        "Butterflies taste with their feet.",
        "The slipper-shelled snail starts life as a male and gradually turns female as it grows up.",
        "Parthenophobia is the fear of virgins.",
        "Almonds are a member of the peach family.",
        "The word \"PEZ\" comes from the German word for peppermint, PfeffErminZ",
        "In Peanuts in 1968, Snoopy trained to become a champion arm-wrestler. In the end, he was disqualified for not having thumbs.",
        "Belmont University once offered a course called \"Oh, Look, a Chicken! Embracing Distraction as a Way of Knowing.\"",
        "After an online vote in 2011, Toyota announced that the official plural of Prius was Prii.",
        "The only number whose letters are in alphabetical order is 40 (f-o-r-t-y).",
        "The string on boxes of animal crackers was originally placed there so the container could be hung from a Christmas tree.",
        "Only female mosquitoes will bite you.",
        "In the 1970s, Mattel sold a doll called \"Growing Up Skipper.\" Her breasts grew when her arm was turned.",
        "M&M’s actually stands for \"Mars & Murrie’s,\" the last names of the candy’s founders.",
        "The 3 Musketeers bar was originally split into three pieces with three different flavors: vanilla, chocolate and strawberry. When the other flavors became harder to come by during World War II, Mars decided to go all chocolate.",
        "Camels chew in a figure 8 pattern.",
        "A skunk’s smell can be detected by a human a mile away.",
        "Koalas never drink water. They get fluids from the eucalyptus leaves they eat.",
        "The cheetah is the only cat that can’t retract its claws.",
        "A cat uses its whiskers to determine if a space is too small to squeeze through.",
        "All letters addressed to Santa in the United States go to Santa Claus, Indiana",
        "Beethoven dipped his head in cold water before he composed.",
        "Barbie’s full name is \"Babara Millicent Roberts.\"",
        "An average human scalp has 100,000 hairs.",
        "Blondes have more hair than dark-haired people do.",
        "Australian soldiers used the song \"We’re Off to See the Wizard\" as a marching song in WWII.",
        "Antarctica is the only continent that does not have land areas below sea level.",
        "Netherlands is the only country with a national dog.",
        "When we think of Big Ben in London, we think of the clock. Actually, it’s the bell.",
        "No matter where you stand in Michigan, you are never more than 85 miles from a Great Lake.",
        "The official beverage of Ohio is tomato juice.",
        "In Quebec, there is an old law that states margarine must be a different color than butter.",
        "Denver, Colorado lays claim to the invention of the cheeseburger.",
        "In Utah, it is illegal to swear in front of a dead person.",
        "Salt Lake City, Utah has a law against carrying an unwrapped ukulele on the street.",
        "It is illegal to hunt camels in the state of Arizona.",
        "More people are allergic to cow’s milk than any other food.",
        "A female ferret will die if it goes into heat and cannot find a mate.",
        "John Adams, Thomas Jefferson, and James Monroe died on July 4th.",
        "Stephen Hawking was born exactly 300 years after Galileo died.",
        "\"Lassie\" was played by a group of male dogs; the main one was named Pal.",
        "Abraham Lincoln’s ghost is said to haunt the White House.",
        "Scotland has more redheads than any other part of the world.",
        "A shrimp’s heart is in its head.",
        "A healthy (non-colorblind) human eye can distinguish between 500 shades of gray.",
        "A \"jiffy\" is the scientific name for 1/100th of a second.",
        "The youngest pope ever was 11 years old.",
        "Hedenophobic means fear of pleasure.",
        "Every year 4 people in the UK die putting their trousers on.",
        "Intelligent people have more zinc and copper in their hair.",
        "The world’s youngest parents were 8 and 9 and lived in China in 1910.",
        "Grapes explode when you put them in the microwave.",
        "In The Empire Strikes Back there is a potato hidden in the asteroid field.",
        "Walt Disney holds the world record for the most Academy Awards won by one person, he has won twenty statuettes, and twelve other plaques and certificates.",
        "James Bond’s car had three different license plates in Goldfinger.",
        "The very first song played on MTV was ‘Video Killed The Radio Star’ by the Buggles.",
        "Bullet proof vests, fire escapes, windshield wipers, and laser printers were all invented by women.",
        "In Disney’s Fantasia, the Sorcerer’s name is \"Yensid\" (Disney backwards.)",
        "It was discovered on a space mission that a frog can throw up. The frog throws up its stomach first, so the stomach is dangling out of its mouth. Then the frog uses its forearms to dig out all of the stomach’s contents and then swallows the stomach back down.",
        "Pearls melt in vinegar.",
        "Humans are the only primates that don’t have pigment in the palms of their hands.",
        "The fingerprints of koala bears are virtually indistinguishable from those of humans, so much so that they can be easily confused at a crime scene.",
        "The first owner of the Marlboro company died of lung cancer.",
        "Walt Disney was afraid of mice.",
        "The king of hearts is the only king without a mustache.",
        "Simplistic passwords contribute to over 80% of all computer password break-ins.",
        "The top 3 health-related searches on the Internet are (in this order): Depression, Allergies, & Cancer.",
        "NBA superstar Michael Jordan was originally cut from his high school basketball team.",
        "You spend 7 years of your life in the bathroom.",
        "Shakespeare is quoted 33,150 times in the Oxford English dictionary.",
        "The word Pennsylvania is misspelled on the Liberty Bell.",
        "A spider has transparent blood.",
        "Van Gogh only sold one painting when he was alive.",
        "A standard slinky measures 87 feet when stretched out.",
        "Rubber bands last longer when refrigerated.",
        "Virginia Woolf wrote all her books standing",
        "The scene where Indiana Jones shoots the swordsman in Raider’s of the Lost Ark was Harrison Ford’s idea so that he could take a bathroom break.",
        "Mozart wrote the nursery rhyme 'twinkle, twinkle, little star' at the age of 5.",
        "In the Philippine jungle, the yo-yo was first used as a weapon.",
        "The name of the girl on the statue of liberty is Mother of Exiles.",
        "It is illegal to eat oranges while bathing in California.",
        "Non-dairy creamer is flammable.",
        "Each king in a deck of playing cards represents a great king from history. Spades – King David, Clubs – Alexander the Great, Hearts – Charlemagne, and Diamonds – Julius Caesar.",
        "The only 15-letter word that can be spelled without repeating a letter is uncopyrightable.",
        "Emus and kangaroos cannot walk backwards, and are on the Australian coat of arms for that reason.",
        "Blueberry Jelly Bellies were created especially for Ronald Reagan.",
        "Honking of car horns for a couple that just got married is an old superstition to insure great sex.",
        "40,000 Americans are injured by toilets each year.",
        "You can be fined up to $1,000 for whistling on Sunday in Salt Lake City, Utah.",
        "Honey is the only food which does not spoil.",
        "Hot water is heavier than cold.",
        "The most common name in world is Mohammed.",
        "The word \"lethologica\" describes the state of not being able to remember the word you want.",
        "People photocopying their buttocks are the cause of 23% of all photocopier faults worldwide.",
        "The storage capacity of human brain exceeds 4 Terabytes.",
        "Any free-moving liquid in outer space will form itself into a sphere, because of its surface tension.",
        "In 1999, Furbies were banned from the National Security Agency’s Maryland headquarters because it was feared the toys might repeat national security secrets.",
        "When a Hawaiian woman wears a flower over her left ear, it means that she is not available.",
        "Coca-Cola was originally green.",
        "The average person spends about two years on the phone in a lifetime.",
        "The Human eyes never grow, but nose and ears never stop growing.",
        "The shortest war in history was between Zanzibar and England in 1896. Zanzibar surrendered after 38 minutes.",
        "1 in 8 Americans has worked at a McDonalds restaurant.",
        "A pregnant goldfish is called a twit.",
        "Celery has negative calories! It takes more calories to eat a piece of celery than the celery has in it.",
        "You burn more calories sleeping than you do watching TV.",
        "If one places a tiny amount of liquor on a scorpion, it will instantly go mad and sting itself to death.",
        "The plastic things on the end of shoelaces are called aglets.",
        "There is approximately one chicken for every human being in the world.",
        "Women manage the money and pay the bills in 75% of all Americans households.",
        "Ninety percent of all species that have become extinct have been birds.",
        "The electric chair was invented by a dentist.",
        "A whale’s penis is called a dork.",
        "Reindeer like to eat bananas.",
        "Mel Blanc (the voice of Bugs Bunny) was allergic to carrots.",
        "101 Dalmatians, Peter Pan, Lady and the Tramp, and Mulan are the only Disney cartoons where both parents are present and don’t die throughout the movie.",
        "The state flower of Alaska is a forget-me-not.",
        "Octavio Guillen and Adriana Martinez were married in Mexico City in 1969 after a world record engagement of 67 years.",
        "Teddy Roosevelt had four sons. Three of them died in war.",
        "An electric eel will short-circuit itself if put into salt water.",
        "Kilts originated in France, not Scotland.",
        "According to ancient Hindu law, the penalty for adultery was the removal of a person’s nose.",
        "Most snakes can go without eating for an entire year.",
        "Most monkeys are nearsighted.",
        "It is against the law to sing out of tune in North Carolina.",
        "A newborn baby cannot shed tears.",
        "Only righthanded players can play polo according to the U.S. Polo Association.",
        "Coffee is the world’s most recognizable smell.",
        "Insects can shiver.",
        "New Mexico is the only US state with two official languages – English and Spanish.",
        "Lightning is the cause of most forest fires.",
        "In China, the day a child is born it is considered one year old.",
        "Abraham Lincoln was carrying Confederate money when he was assassinated.",
        "The sound you hear in a seashell is actually the echo of the blood pulsing in your ear.",
        "Rabbits talk to each other by tapping their feet.",
        "Fish can become seasick if kept aboard a ship.",
        "A fetus in the womb can get hiccups.",
        "There are eleven time zones in Russia.",
        "President Zachary Taylor never voted in a presidential election – not even his own.",
        "France’s King Louis XIV was on the throne so long he was succeeded by his great grandson.",
        "Jousting is the official state sport of Maryland.",
        "Jellyfish evaporate every once in a while.",
        "Sahara means desert in Arabic so the \"Sahara Desert\" is the \"Desert Desert\"",
        "Months that start with Sunday, have Friday the 13th",
        "There are Victoria's Secret models from every continent except Antarctica.",
        "Wolfeschlegelsteinhausenbergerdorff is the longest recorded personal name",
        "Cotton Candy was created by a dentist and originally called \"Fairy Floss\"",
        "Many nursing homes in Germany have fake bus stops to round up dementia patients",
        "In Texas, it's illegal to kill Bigfoot if you ever find him",
        "The King of Norway is 73rd in line to the British throne.",
        "Christmas was illegal in the U.S. until 1836 as it was considered an Ancient Pagan Holiday.",
        "The white thin film over the tongue is actually bacteria build up. A pink tongue represents a healthy clean tongue.",
        "Pagophagia is a disorder involving the compulsion to chew ice.",
        "The creator of peanut M&Ms was allergic to peanuts.",
        "The Louvre was never intended to be a museum. It was built as a fortress in 1190 to protect the City of Paris.",
        "There are 4 states in the U.S. that ban oral sex but allow necrophilia.",
        "The first online transaction ever was Stanford students buying marijuana from MIT students.",
        "After 3 months in the womb, a fetus already has a preference for which hand it uses the most.",
        "A natural predator of the Moose is the Killer Whale. They have been known to prey on moose swimming around America's Northwest Coast.",
        "Around 42% of Americans play video games regularly.",
        "Squirrels will adopt other squirrels babies if they are abandoned.",
        "The design for Gene Roddenberry's USS Enterprise is based on a heating coil from an electric stove",
        "Besides February 29, Christmas is the least common birthday.",
        "Olympic gold medals are actually made mostly of silver",
        "You are born with 300 bones; by the time you are an adult you will have 206",
        "It takes about 8 minutes for the light from the Sun to reach Earth",
        "Some bamboo plants can grow almost a meter in just one day",
        "The state of Florida is bigger than England",
        "Some penguins can leap 2-3 meters out of the water",
        "On average, it takes 66 days to form a new habit",
        "Mammoths still walked the Earth when the Great Pyramid was being built"]
    
    func randomFact() -> String {
        let randomNumber = GKRandomSource.sharedRandom().nextInt(upperBound: facts.count)
        return facts[randomNumber]
    }
}
